name = "synthetix-sample-project"
version = "<%= package.version %>"
description = "Sample usage of the router manager"

# `salt` here only affects proxy contract
[setting.salt]
description = "Change this to a unique string when deploying multiple instances of the system. Note that only the proxy contract will be unique."
defaultValue = "main"

[setting.owner]
description = "Admin user for the system"
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.OwnerModule]
artifact = "contracts/modules/OwnerModule.sol:OwnerModule"

[contract.UpgradeModule]
artifact = "contracts/modules/UpgradeModule.sol:UpgradeModule"

[contract.InitializableModule]
artifact = "InitializableModule"

[contract.SettingsModule]
artifact = "SettingsModule"

[contract.SomeModule]
artifact = "SomeModule"

[contract.AnotherModule]
artifact = "AnotherModule"

[run.generate_router]
exec = "../hardhat-router/dist/cannon/router.js"
func = "generate"
args = ["Router", "contracts/modules"]
modified = []
depends = [
  "contract.OwnerModule",
  "contract.UpgradeModule",
  "contract.InitializableModule",
  "contract.SettingsModule",
  "contract.SomeModule",
  "contract.AnotherModule"
]

[contract.Router]
artifact = "contracts/routers/chain-<%= chainId %>/Router.sol:Router"
abiOf = [
  "OwnerModule",
  "UpgradeModule",
  "InitializableModule",
  "SettingsModule",
  "SomeModule",
  "AnotherModule"
]
depends = ["run.generate_router"]

[contract.Proxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= contracts.Router.address %>"]
abiOf = ["Router"]
depends = ["contract.Router"]
