name = "core-sandbox-consumer-example"
version = "1"
description = "Consumer of LP Sandbox"

[import.core_sandbox]
source = "core-sandbox"

[setting.test_user]
defaultValue = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" # PK 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
description = "Hardhat/Anvil second test account"

[setting.test_user_account_id]
defaultValue = "69"

[setting.test_user_perps_account_id]
defaultValue = "420"

#
#
#
# Interacting with Core
#
#
#
[invoke.create_account]
target = ["core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "createAccount(uint128)"
args = ["<%= settings.test_user_account_id %>"]
extra.test_user_account_id.event = "AccountCreated"
extra.test_user_account_id.arg = 0

[invoke.mint_10k_box]
target = ["core_sandbox.box_token.MintableToken"]
from = "<%= settings.test_user %>"
func = "mint"
args = ["<%= parseEther('10000') %>", "<%= settings.test_user %>"]

[invoke.approve_10k_box_for_CoreProxy_to_spend]
target = ["core_sandbox.box_token.MintableToken"]
from = "<%= settings.test_user %>"
func = "approve"
args = [
    "<%= imports.core_sandbox.imports.synthetix.contracts.CoreProxy.address %>",
    "<%= parseEther('10000') %>",
]
depends = ["invoke.mint_10k_box"]

[invoke.deposit_1k_box]
target = ["core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "deposit"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('1000') %>",
]
depends = ["invoke.approve_10k_box_for_CoreProxy_to_spend"]

[invoke.delegate_900_box]
target = ["core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "delegateCollateral"
args = [
    # examples of how to debug internal values line by line
    "<%= /* console.log(extras) || */ extras.test_user_account_id %>",
    "<%= /* console.log(imports.core_sandbox.extras) || */imports.core_sandbox.extras.spartan_council_pool_id %>",
    "<%= /* console.log(imports.core_sandbox.imports) || */ imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('900') %>",
    "<%= parseEther('1') %>",
]
depends = ["invoke.deposit_1k_box"]

[invoke.borrow_300_susd]
target = ["core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "mintUsd"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.core_sandbox.extras.spartan_council_pool_id %>",
    "<%= imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('300') %>",
]
depends = ["invoke.delegate_900_box"]

[invoke.withdraw_300_susd]
target = ["core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "withdraw"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.core_sandbox.imports.synthetix.contracts.USDProxy.address %>",
    "<%= parseEther('300') %>",
]
depends = ["invoke.borrow_300_susd"]
