name = "synthetix-governance"
description = "Governance cotracts for on chain voting"
version = "0.0.1"

# Deployment Owner, defaults to first hardhat account
[setting.owner_address]
defaultValue = "0xe3B0C44298FC1C149AfBF4C8996fb92427aE41E4"

[setting.council_token_name]
defaultValue = "Synthetix Governance Module"

[setting.council_token_symbol]
defaultValue = "SGT"

[setting.first_council_member]
defaultValue = "0xe3B0C44298FC1C149AfBF4C8996fb92427aE41E4"

[setting.epoch_duration]
defaultValue = 90 # days

[setting.voting_period_duration]
defaultValue = 7 # days

[contract.election_module]
artifact = "contracts/modules/ElectionModule.sol:ElectionModule"
step = 1

[contract.owner_module]
artifact = "contracts/modules/OwnerModule.sol:OwnerModule"
step = 1

[contract.upgrade_module]
artifact = "contracts/modules/UpgradeModule.sol:UpgradeModule"
step = 1

[run.generate_router]
exec = "scripts/generate-router.js"
func = "generateRouter"
args = ['''
{
  "contracts/modules/ElectionModule.sol:ElectionModule": "<%= outputs.self.contracts.election_module.address %>",
  "contracts/modules/OwnerModule.sol:OwnerModule": "<%= outputs.self.contracts.owner_module.address %>",
  "contracts/modules/UpgradeModule.sol:UpgradeModule": "<%= outputs.self.contracts.upgrade_module.address %>"
}
''']
step = 2

[contract.router]
artifact = "contracts/Router.sol:Router"
step = 3

[contract.proxy]
artifact = "contracts/Proxy.sol:Proxy"
args = ["<%= outputs.self.contracts.router.address %>"]
step = 4

[invoke.initialize_owner_module]
addresses = ["<%= outputs.self.contracts.proxy.address %>"]
abi = "<%= outputs.self.contracts.owner_module.abi %>"
func = "initializeOwnerModule"
args = ["<%= settings.owner_address %>"]
step = 5

[run.epoch_dates]
exec = "scripts/calculate-epoch-dates.js"
func = "calculateEpochDates"
args = [
  "<%= settings.epoch_duration %>",
  "<%= settings.voting_period_duration %>",
]
step = 6

[contract.debt_share_mock]
artifact = "contracts/mocks/DebtShareMock.sol:DebtShareMock"
step = 7

[invoke.initialize_election_module]
addresses = ["<%= outputs.self.contracts.proxy.address %>"]
abi = "<%= outputs.self.contracts.election_module.abi %>"
func = "initializeElectionModule"
args = [
  "<%= settings.council_token_name %>",
  "<%= settings.council_token_symbol %>",
  ["0xe3B0C44298FC1C149AfBF4C8996fb92427aE41E4"], # TODO: allow array settings interpolation: <%= settings.first_council_members %>,
  "1",
  "<%= outputs.self.runs.epoch_dates.nominationPeriodStartDate %>",
  "<%= outputs.self.runs.epoch_dates.votingPeriodStartDate %>",
  "<%= outputs.self.runs.epoch_dates.epochEndDate %>",
  "<%= outputs.self.contracts.debt_share_mock.address %>",
]
step = 7
