name = "synthetix-governance"
description = "Governance cotracts for on chain voting"
version = "0.0.1"

[contract.election_module]
artifact = "contracts/modules/ElectionModule.sol:ElectionModule"
step = 1

[contract.owner_module]
artifact = "contracts/modules/OwnerModule.sol:OwnerModule"
step = 1

[contract.upgrade_module]
artifact = "contracts/modules/UpgradeModule.sol:UpgradeModule"
step = 1

[run.upgrade_module]
exec = "scripts/generate-router.js"
func = "generateRouter"
step = 2
args = [
  "contracts/modules/ElectionModule.sol:ElectionModule",
  "<%= outputs.self.contracts.election_module.address %>",
  "contracts/modules/OwnerModule.sol:OwnerModule",
  "<%= outputs.self.contracts.owner_module.address %>",
  "contracts/modules/UpgradeModule.sol:UpgradeModule",
  "<%= outputs.self.contracts.upgrade_module.address %>"
]

[contract.router]
artifact = "contracts/Router.sol:Router"
step = 2

[contract.proxy]
artifact = "contracts/Proxy.sol:Proxy"
step = 3
args = ["<%= outputs.self.contracts.router.address %>"]
