[profile.default]
src = 'contracts'
out = 'out'
libs = ['node_modules', 'lib']
test = 'test'
cache_path  = 'cache_forge'

remappings = [
    "forge-std=lib/forge-std/src",
    "@synthetixio=../../node_modules/@synthetixio",
]

fs_permissions = [{ access = "read", path = "../../" }]

allow_paths = ["../../"]