name = "wsteth-to-steth-ratio-oracle"
version = "<%= package.version %>-testable"

# --- Imports --- #

[pull.synthetix]
source = "synthetix:latest"

# --- wstETH mock (Lido contracts) --- #

[deploy.WstETHMock]
artifact = "contracts/mocks/WstETHMock.sol:WstETHMock"

[deploy.WstEthToStEthRatioOracle]
artifact = "contracts/WstEthToStEthRatioOracle.sol:WstEthToStEthRatioOracle"
args = ["<%= contracts.WstETHMock.address %>"]

[invoke.register_node_wsteth_to_steth_ratio_oracle]
target = ["synthetix.oracle_manager.Proxy"]
func = "registerNode"
args = [
    # external node
    2,
    # contract
    "<%= defaultAbiCoder.encode(['address'], [contracts.WstEthToStEthRatioOracle.address]) %>",
    [
    ],
]
var.wsteth_to_steth_ratio_oracle_node_id.event = "NodeRegistered"
var.wsteth_to_steth_ratio_oracle_node_id.arg = 0
depends = ["contract.WstETHMock", "contract.WstEthToStEthRatioOracle"]

# --- CL stETH/USD oracle --- #

[deploy.StEthAggregatorV3MockOracleNode]
artifact = "contracts/mocks/AggregatorV3Mock.sol:AggregatorV3Mock"
args = []

[invoke.register_node_steth_aggregator_v3_mock_oracle_node]
target = ["synthetix.oracle_manager.Proxy"]
func = "registerNode"
args = [
    # chainlink aggregator type
    3,
    # contract, twap, decimals
    "<%= defaultAbiCoder.encode(['address', 'uint256', 'uint8'], [contracts.StEthAggregatorV3MockOracleNode.address, 0, 18]) %>",
    [
    ],
]
var.steth_aggregator_v3_mock_oracle_node_id.event = "NodeRegistered"
var.steth_aggregator_v3_mock_oracle_node_id.arg = 0
depends = ["contract.StEthAggregatorV3MockOracleNode"]

# --- wstETH/USD oracle --- #

[invoke.register_node_wsteth_oracle_node]
target = ["synthetix.oracle_manager.Proxy"]
func = "registerNode"
args = [
    # reducer node
    1,
    # mulDecimal
    "<%= defaultAbiCoder.encode(['uint256'], [7]) %>",
    # stETH/USD, wstETH/stETH
    [
        "<%= settings.steth_aggregator_v3_mock_oracle_node_id %>",
        "<%= settings.wsteth_to_steth_ratio_oracle_node_id %>",
    ],
]
var.wsteth_oracle_node_id.event = "NodeRegistered"
var.wsteth_oracle_node_id.arg = 0
depends = [
    "import.synthetix",
    "invoke.register_node_wsteth_to_steth_ratio_oracle",
    "invoke.register_node_steth_aggregator_v3_mock_oracle_node",
]
