name = "wsteth-to-steth-ratio-oracle"
version = "<%= package.version %>"
description = "<%= package.description %>"

# @see: https://etherscan.io/token/0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0
[var.main]
wsteth = "0x7f39c581f595b53c5cb19bd0b3f8da6c935e2ca0"

[deploy.WstEthToStEthRatioOracle]
artifact = "contracts/WstEthToStEthRatioOracle.sol:WstEthToStEthRatioOracle"
args = ["<%= settings.wsteth %>"]
