module.exports = {
  SUBTASK_DEPLOY_CONTRACT: 'deploy-contract',
  SUBTASK_DEPLOY_CONTRACTS: 'deploy-contracts',
  SUBTASK_DEPLOY_MODULES: 'generate-deploy-modules',
  SUBTASK_DEPLOY_ROUTER: 'generate-deploy-router',
  SUBTASK_GENERATE_IMC_SOURCE: 'generate-imc-source',
  SUBTASK_GENERATE_ROUTER_SOURCE: 'generate-router-source',
  SUBTASK_PREPARE_DEPLOYMENT: 'prepare-deployment',
  SUBTASK_PRINT_INFO: 'print-info',
  SUBTASK_SYNC_SOURCES: 'sync-sources',
  SUBTASK_UPGRADE_PROXY: 'upgrade-proxy',
  SUBTASK_VALIDATE_IMC: 'validate-imc',
  SUBTASK_VALIDATE_ROUTER: 'validate-router',
  TASK_DEPLOY: 'deploy',
};
