module.exports = {
  SUBTASK_CANCEL_DEPLOYMENT: 'deployer-cancel-deployment',
  SUBTASK_CLEAR_DEPLOYMENTS: 'deployer-clear-deployments',
  SUBTASK_DEPLOY_CONTRACT: 'deployer-deploy-contract',
  SUBTASK_DEPLOY_CONTRACTS: 'deployer-deploy-contracts',
  SUBTASK_DEPLOY_MODULES: 'deployer-generate-deploy-modules',
  SUBTASK_DEPLOY_ROUTER: 'deployer-generate-deploy-router',
  SUBTASK_GENERATE_ROUTER_SOURCE: 'deployer-generate-router-source',
  SUBTASK_PREPARE_DEPLOYMENT: 'deployer-prepare-deployment',
  SUBTASK_LOAD_DEPLOYMENT: 'deployer-load-deployment',
  SUBTASK_PRINT_INFO: 'deployer-print-info',
  SUBTASK_SYNC_PROXY: 'deployer-sync-proxy',
  SUBTASK_SYNC_SOURCES: 'deployer-sync-sources',
  SUBTASK_UPGRADE_PROXY: 'deployer-upgrade-proxy',
  SUBTASK_VALIDATE_MODULES: 'deployer-validate-modules',
  SUBTASK_VALIDATE_STORAGE: 'deployer-validate-storage',
  SUBTASK_VALIDATE_ROUTER: 'deployer-validate-router',
  TASK_DEPLOY: 'deploy',
};
