name = "synthetix-treasury-market"
version = "<%= package.version %>"
description = ""

[setting.owner] # this has to be the same owner as CoreProxy
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.treasury_address]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.pool_id]
defaultValue = "1"

[setting.collateral_token]
defaultValue = "<%= imports.v3.contracts.USDProxy.address %>"

[setting.v3_package]
defaultValue = "synthetix:latest"

[setting.aux_token]
defaultValue = "<%= AddressZero %>"

[setting.aux_recipient]
defaultValue = "<%= AddressZero %>"

[setting.aux_reset_time]
defaultValue = "<%= 86400 * 7 %>"

[setting.required_aux_token_ratio]
defaultValue = "0"

[pull.v3]
source = "<%= settings.v3_package %>"

[deploy.InitialModuleBundle]
artifact = "InitialModuleBundle"
create2 = true
ifExists = "continue"

[deploy.InitialProxy]
artifact = "SynthetixTreasuryProxy"
args = ["<%= contracts.InitialModuleBundle.address %>", "<%= settings.owner %>"]
abiOf = ["InitialModuleBundle"]
create2 = true

# deploy the legacy market
[deploy.MarketImpl]
artifact = "TreasuryMarket"
args = [
    "<%= imports.v3.contracts.CoreProxy.address %>",
    "<%= imports.v3.imports.oracle_manager.contracts.Proxy.address %>",
    "<%= settings.treasury_address %>",
    "<%= settings.pool_id %>",
    "<%= settings.collateral_token %>",
]
create2 = true
ifExists = "continue"

[deploy.Staking]
artifact = "TreasuryStakingRewards"
args = [
    "<%= settings.aux_token %>",
    "<%= contracts.InitialProxy.address %>",
    "<%= settings.aux_recipient %>",
]

[invoke.upgradeProxy]
target = ["InitialProxy"]
abi = "UpgradeModule"
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.MarketImpl.address %>"]
factory.Proxy.abiOf = ["MarketImpl"]
factory.Proxy.artifact = "SynthetixTreasuryProxy"
factory.Proxy.constructorArgs = [
    "<%= contracts.InitialModuleBundle.address %>",
    "<%= settings.owner %>",
]
factory.Proxy.event = "Upgraded"
factory.Proxy.arg = 0
factory.Proxy.highlight = true

[invoke.setAuxTokenRewards]
target = ["Proxy"]
from = "<%= settings.owner %>"
func = "updateAuxToken"
args = [
    "<%= contracts.Staking.address %>",
    "<%= settings.required_aux_token_ratio %>",
    "<%= settings.aux_reset_time %>",
]

[invoke.setFeatureFlagMarket]
target = ["v3.CoreProxy"]
func = "addToFeatureFlagAllowlist"
args = [
    "<%= formatBytes32String('registerMarket') %>",
    "<%= contracts.Proxy.address %>",
]
fromCall.func = "owner"

[invoke.setFeatureFlagAssociateDebt]
target = ["v3.CoreProxy"]
func = "addToFeatureFlagAllowlist"
args = [
    "<%= formatBytes32String('associateDebt') %>",
    "<%= contracts.Proxy.address %>",
]
fromCall.func = "owner"

[invoke.registerMarket]
target = ["Proxy"]
from = "<%= settings.owner %>"
func = "registerMarket"
args = []
extra.market_id.event = "MarketRegistered"
extra.market_id.arg = 1
depends = ["invoke.setFeatureFlagMarket"]
