include = ["cannonfile.toml"]

[invoke.configureSnxCollateral]
target = ["v3.CoreProxy"]
func = "configureCollateral"
args = [
    { tokenAddress = "<%= imports.v2x.contracts.ProxySynthetix.address %>", oracleNodeId = "<%= imports.v3.extras.const_one_oracle_id %>", issuanceRatioD18 = "3000000000000000000", liquidationRatioD18 = "2000000000000000000", liquidationRewardD18 = "1000000000000000000", minDelegationD18 = "1000000000000000000", depositingEnabled = true },
]
fromCall.func = "owner"

[invoke.authorizedBroker]
target = ["v2x.SynthetixDebtShare"]
func = "addAuthorizedBroker"
args = ["<%= contracts.Proxy.address %>"]
fromCall.func = "owner"

# create spartan council pool
[invoke.createPool]
target = ["v3.CoreProxy"]
from = "<%= settings.pool_owner %>"
func = "createPool"
args = ["<%= settings.sc_pool_id %>", "<%= settings.pool_owner %>"]
depends = ["invoke.setFeatureFlagPool"]

[invoke.configurePool]
target = ["v3.CoreProxy"]
func = "setPoolConfiguration"
from = "<%= settings.pool_owner %>"
args = [
    "<%= settings.sc_pool_id %>",
    [
        { marketId = "<%= extras.marketId %>", weightD18 = "1", maxDebtShareValueD18 = "1000000000000000000" },
    ],
]
depends = ["invoke.createPool"]

[invoke.preferPool]
target = ["v3.CoreProxy"]
func = "setPreferredPool"
args = ["<%= settings.sc_pool_id %>"]
fromCall.func = "owner"
depends = ["invoke.createPool"]

[invoke.registerRewardsDistributor]
target = ["v3.CoreProxy"]
func = "registerRewardsDistributor"
args = [
    "<%= settings.sc_pool_id %>",
    "<%= imports.v2x.contracts.ProxySynthetix.address %>",
    "<%= contracts.SNXDistributor.address %>",
]

fromCall.func = "owner"

depends = ["invoke.createPool", "contract.SNXDistributor"]
