name = "synthetix-rewards-dist-ext"
version = "<%= package.version %>"
description = "Rewards distributor (approved to an external distributor) for Core Synthetix v3"

[setting.salt]
defaultValue = "rewards"

[setting.rewardManager]
# CoreProxy
defaultValue = "0x32C222A9A159782aFD7529c87FA34b96CA72C696"
description = "Reward manager address"

[setting.authorizedDistributor]
# i.e. PerpsProxy
defaultValue = "0x0A2AF931eFFd34b81ebcc57E3d3c9B1E1dE1C9Ce"
description = "Authorized Distributor address (PerpsProxy, etc.)"

[setting.poolId]
# Spartan Council pool on Base Mainnet
defaultValue = "1"
description = "Associated Pool ID"

[setting.collateralType]
# USDC on Base Mainnet
defaultValue = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
description = "Token address of the pool collateral"

[setting.payoutToken]
# SNX on Base Mainnet
defaultValue = "0x22e6966B799c4D5B13BE962E1D117b56327FDa66"
description = "Rewards token address"

[setting.payoutTokenDecimals]
defaultValue = "18"
description = "Decimals of the payout token"

[setting.name]
defaultValue = "Rewards Distributor (External) V3"
description = "Rewards distributor (External) name"

[contract.RewardsDistributorExternal]
artifact = "RewardsDistributorExternal"
args = [
    "<%= settings.rewardManager %>",
    "<%= settings.poolId %>",
    "<%= settings.collateralType %>",
    "<%= settings.payoutToken %>",
    "<%= settings.payoutTokenDecimals %>",
    "<%= settings.name %>",
    "<%= settings.authorizedDistributor %>",
]
