name = "synthetix-rewards-dist-ext"
version = "<%= package.version %>"
description = "Rewards distributor (approved to an external distributor) for Core Synthetix v3"

[var.main]
salt = "rewards"
rewardManager = "0x32C222A9A159782aFD7529c87FA34b96CA72C696"
authorizedDistributor = "0x0A2AF931eFFd34b81ebcc57E3d3c9B1E1dE1C9Ce"
poolId = "1"
collateralType = "0x833589fcd6edb6e08f4c7c32d4f71b54bda02913"
payoutToken = "0x22e6966B799c4D5B13BE962E1D117b56327FDa66"
payoutTokenDecimals = "18"
name = "Rewards Distributor (External) V3"

[deploy.RewardsDistributorExternal]
artifact = "RewardsDistributorExternal"
args = [
    "<%= settings.rewardManager %>",
    "<%= settings.poolId %>",
    "<%= settings.collateralType %>",
    "<%= settings.payoutToken %>",
    "<%= settings.payoutTokenDecimals %>",
    "<%= settings.name %>",
    "<%= settings.authorizedDistributor %>",
]
