[import.v3]
source = "synthetix:3"

[contract.market]
artifact = "SimpleSpotMarket"
# args = ["<%= imports.v2x.contracts.AddressResolver.address", "<%= imports.v3.contracts.CoreProxy.address %>"]

[invoke.registerMarket]
target = ["v3.CoreProxy"]
func = "registerMarket"
args = ["<%= contracts.market.address %>"]

# TODO: build periphery