name = "perps-sandbox-consumer-example"
version = "2"
description = "Consumer of Perps Sandbox"

[import.perps_sandbox]
source = "perps-sandbox:2"

[setting.test_user]
defaultValue = "0x70997970C51812dc3A010C7d01b50e0d17dc79C8" # PK 0x59c6995e998f97a5a0044966f0945389dc9e86dae88c7a8412f4603b6b78690d
description = "Hardhat/Anvil second test account"

[setting.test_user_account_id]
defaultValue = "69"

[setting.test_user_perps_account_id]
defaultValue = "420"

[setting.another_user]
defaultValue = "0xa0Ee7A142d267C1f36714E4a8F75612F20a79720" # PK 0x2a871d0798f97d79848a013d4936a73bf4cc922c825d33c1cf7073dff6d409c6
description = "Hardhat/Anvil test account (9)"

#
#
#
# Interacting with Core
#
#
#
[invoke.create_account]
target = ["perps_sandbox.core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "createAccount(uint128)"
args = ["<%= settings.test_user_account_id %>"]
extra.test_user_account_id.event = "AccountCreated"
extra.test_user_account_id.arg = 0

[invoke.mint_10k_box]
target = ["perps_sandbox.core_sandbox.box_token.MintableToken"]
from = "<%= settings.test_user %>"
func = "mint"
args = ["<%= parseEther('10000') %>", "<%= settings.test_user %>"]

[invoke.approve_10k_box_for_CoreProxy_to_spend]
target = ["perps_sandbox.core_sandbox.box_token.MintableToken"]
from = "<%= settings.test_user %>"
func = "approve"
args = [
    "<%= imports.perps_sandbox.imports.core_sandbox.imports.synthetix.contracts.CoreProxy.address %>",
    "<%= parseEther('10000') %>",
]
depends = ["invoke.mint_10k_box"]

[invoke.deposit_1k_box]
target = ["perps_sandbox.core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "deposit"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.perps_sandbox.imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('1000') %>",
]
depends = ["invoke.approve_10k_box_for_CoreProxy_to_spend"]

[invoke.delegate_900_box]
target = ["perps_sandbox.core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "delegateCollateral"
args = [
    # examples of how to debug internal values line by line
    "<%= /*console.log(extras) ||*/ extras.test_user_account_id %>",
    "<%= /*console.log(imports.perps_sandbox.extras) ||*/ imports.perps_sandbox.imports.core_sandbox.extras.spartan_council_pool_id %>",
    "<%= /*console.log(imports.perps_sandbox.imports) ||*/ imports.perps_sandbox.imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('900') %>",
    "<%= parseEther('1') %>",
]
depends = ["invoke.deposit_1k_box"]

[invoke.borrow_300_susd]
target = ["perps_sandbox.core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "mintUsd"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.perps_sandbox.imports.core_sandbox.extras.spartan_council_pool_id %>",
    "<%= imports.perps_sandbox.imports.core_sandbox.imports.box_token.contracts.MintableToken.address %>",
    "<%= parseEther('300') %>",
]
depends = ["invoke.delegate_900_box"]

[invoke.withdraw_300_susd]
target = ["perps_sandbox.core_sandbox.synthetix.CoreProxy"]
from = "<%= settings.test_user %>"
func = "withdraw"
args = [
    "<%= extras.test_user_account_id %>",
    "<%= imports.perps_sandbox.imports.core_sandbox.imports.synthetix.contracts.USDProxy.address %>",
    "<%= parseEther('300') %>",
]
depends = ["invoke.borrow_300_susd"]

#
#
#
# Interacting with Perps market
#
#
#
[invoke.create_perps_account]
target = ["perps_sandbox.perps_factory.PerpsMarketProxy"]
from = "<%= settings.test_user %>"
func = "createAccount(uint128)"
args = ["<%= settings.test_user_perps_account_id %>"]
extra.test_user_perps_account_id.event = "AccountCreated"
extra.test_user_perps_account_id.arg = 0
# We want to ensure test user has some susd in their wallet to start interacting with perps market, so adding this dependency step
depends = ["invoke.withdraw_300_susd"]

[invoke.approve_100_susd_for_PerpsMarketProxy_to_spend]
target = ["perps_sandbox.core_sandbox.synthetix.USDProxy"]
from = "<%= settings.test_user %>"
func = "approve"
args = [
    "<%= imports.perps_sandbox.imports.perps_factory.contracts.PerpsMarketProxy.address %>",
    "<%= parseEther('100') %>",
]

[invoke.deposit_100_susd_to_perps]
target = ["perps_sandbox.perps_factory.PerpsMarketProxy"]
from = "<%= settings.test_user %>"
func = "modifyCollateral"
args = [
    "<%= extras.test_user_perps_account_id %>",
    0,                                          # 0 is a special market id for sUSD
    "<%= parseEther('100') %>",
]

# Order settlement cannot be done in toml as it must have time delay,
# At the same time we cannot commit more orders until this one is settled, which could be confusing.
# Commending out this code but keep it for documentation
#
#    [invoke.commit_perps_eth_order]
#    target = ["perps_sandbox.perps_factory.PerpsMarketProxy"]
#    from = "<%= settings.test_user %>"
#    func = "commitOrder" # args below
#    depends = ["invoke.deposit_100_susd_to_perps"]
#
#    [[invoke.commit_perps_eth_order.args]]
#    marketId = "<%= imports.perps_sandbox.extras.perps_eth_market_id %>"
#    accountId = "<%= extras.test_user_perps_account_id %>"
#    sizeDelta = "<%= parseEther('1') %>"
#    settlementStrategyId = "0"
#    acceptablePrice = "<%= parseEther(String(1000 * 1.05)) %>" # 5% slippage
#    referrer = "<%= AddressZero %>"
#    trackingCode = "<%= HashZero %>"
[invoke.transfer_100_susd_to_another_user]
target = ["perps_sandbox.core_sandbox.synthetix.USDProxy"]
from = "<%= settings.test_user %>"
func = "transfer"
args = ["<%= settings.another_user %>", "<%= parseEther('100') %>"]
depends = ["invoke.withdraw_300_susd"]
