name = "synthetix-collateral-snx"
version = "0.0.0"
description = "Creates the spartan council pool"

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.snx_package]
defaultValue = "synthetix:3"

[setting.snx_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[setting.snx_aggregator_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[import.system]
source = "<%= settings.snx_package %>"
options.owner = "<%= settings.owner %>"

[invoke.configure_collateral]
target = ["system.CoreProxy"]
from = "<%= settings.owner %>"
func = "configureCollateral"
args = [
  {
    tokenAddress = "<%= settings.snx_address %>"
    priceFeed = "<%= settings.snx_aggregator_address %>"
    issuanceRatio = "300000000000000000000"
    liquidationRatio = "150000000000000000000"
    liquidationReward = "1000000000000000000"
    minDelegation = "1000000000000000000"
    depositingEnabled = true
  }
]
depends = [
  "import.system"
]