name = "buyback-snx"
version = "<%= package.version %>"
description = "Buys SNX at market price plus premium"

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[contract.BuybackSnx]
artifact = "contracts/BuybackSnx.sol:BuybackSnx"
args = ["<%= settings.owner %>"]
create2 = true


# set treasury

# set premium

# set snx node id

# set snx token

# set usdc token
