name = "trusted-multicall-forwarder"
version = "0.0.4"
description = "ERC-2771 compliant trusted forwarder including Multicall3 functionality with error bubbling"

[setting.salt]
defaultValue = "salt"

[contract.TrustedMulticallForwarder]
artifact = "TrustedMulticallForwarder"
salt = "<%= settings.salt %>"
create2 = true
ifExists = "continue"
