# (required) CCIP Router address (should be one of https://docs.chain.link/ccip/supported-networks/)
# [setting.ccip_router]
# defaultValue = "0x261c05167db67B2b619f9d312e0753f3721ad6E8"
#
[setting.ccip_mothership_chain_id]
defaultValue = "11155111"

[setting.ccip_mothership_selector]
defaultValue = "16015286601757825753"

[contract.CcipRouterMock]
artifact = "contracts/mocks/CcipRouterMock.sol:CcipRouterMock"
create2 = true
