name = "arbitrum-gas-price-oracle"
version = "<%= package.version %>"
description = "Arbiturm Gas Price Oracle Node"

[var.main]
arbGasPriceOracleAddress = "0x000000000000000000000000000000000000006C"

[deploy.ArbGasPriceOracle]
artifact = "contracts/ArbGasPriceOracle.sol:ArbGasPriceOracle"
args = ["<%= settings.arbGasPriceOracleAddress %>"]
create2 = true
