name = "synthetix-collateral-weth"
version = "0.0.0"
description = "Creates the spartan council pool"

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.snx_package]
defaultValue = "synthetix:3"

[setting.weth_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[setting.weth_aggregator_address]
defaultValue = "0x0000000000000000000000000000000000000000"

[import.system]
source = "<%= settings.snx_package %>"

[invoke.configure_collateral]
target = ["system.CoreProxy"]
from = "<%= settings.owner %>"
func = "configureCollateral"
args = [
    "<%= settings.weth_address %>",
    "<%= settings.weth_aggregator_address %>",
    "3000000",
    "1500000",
    "1000000000000000000",
    true
]
depends = [
  "import.system"
]