# THIS IS THE SATELLITE CHAIN, WORMHHOLE CHAIN ID 43 = Snaxchain chain 2192, WORMHOLE CHAIN ID 24 = OP MAINNET https://docs.wormhole.com/wormhole/reference/constants#chain-ids

name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "1"
preset = "test-on-mainnet"

include = ["./cannonfile.satellite.toml", "./tomls/testable-contracts.toml"]

[setting.owner]
defaultValue = "0xe2163dd599067919d1e9108929b568Bf41D3A420"

[setting.salt]
defaultValue = "governance-test-on-mainnet"

# [setting.wormhole_core]
# defaultValue = "0xEe91C335eab126dF5fDB3797EA9d6aD93aeC9722" # https://docs.wormhole.com/wormhole/reference/constants#core-contracts

# [setting.wormhole_relayer]
# defaultValue = "0x27428DD2d3DD32A4D7f7C497eAaa23130d894911" # https://docs.wormhole.com/wormhole/reference/constants#standard-relayer

# [setting.initial_council_member]
# defaultValue = "<%= settings.owner %>"

# [setting.minimum_active_members]
# defaultValue = "1"

# [setting.initial_epoch_index]
# defaultValue = "0"

# [setting.initial_epoch_start_date]
# defaultValue = "1724770371"

# [setting.initial_nomination_period_start_date]
# defaultValue = "1724780371"

# [setting.initial_voting_period_start_date]
# defaultValue = "1724980371"

# [setting.initial_epoch_end_date]
# defaultValue = "1725180371"

# [contract.SnapshotRecordMock]
# artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
# salt = "<%= settings.salt %>"
# create2 = true

# [router.CoreRouter]
# contracts = [
#     # Satellite Core Contracts
#     "AssociatedSystemsModule",
#     "ElectionModuleSatellite",
#     "SnapshotVotePowerModule",
#     "InitialModuleBundle",

#     # Testable storage contracts
#     "TestableCouncilStorage",
#     "TestableBallotStorage",
#     "TestableSnapshotVotePowerStorage",
#     "TestableElectionSettingsStorage",
#     "TestableElectionStorage",
#     "TestableEpochStorage",
# ]

# [invoke.set_registered_emitters]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setRegisteredEmitters"
# args = [["43"], ["0xB3026a683AAC2499e70Bbd988a9411A99b00EBD2"]]

# unset v2x snapshot address
# [invoke.set_snapshot_record_1]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setSnapshotContract"
# args = ["0x45c55BF488D3Cb8640f12F63CbeDC027E8261E79", 0, false]
# 
# [invoke.set_snapshot_record_2]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setSnapshotContract"
# args = ["<%= contracts.SnapshotRecordMock.address %>", 0, true]

# [invoke.set_gas_limit]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setGasLimit"
# args = ["10000000"]
