name = "synthetix-governance"
version = "<%= package.version %>-testable"
include = ["cannonfile.toml"]

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"

# Testable storage contracts
[contract.TestableCouncilStorage]
artifact = "contracts/generated/test/TestableCouncilStorage.sol:TestableCouncilStorage"

[contract.TestableBallotStorage]
artifact = "contracts/generated/test/TestableBallotStorage.sol:TestableBallotStorage"

[contract.TestableSnapshotVotePowerStorage]
artifact = "contracts/generated/test/TestableSnapshotVotePowerStorage.sol:TestableSnapshotVotePowerStorage"

[contract.TestableElectionSettingsStorage]
artifact = "contracts/generated/test/TestableElectionSettingsStorage.sol:TestableElectionSettingsStorage"

[contract.TestableElectionStorage]
artifact = "contracts/generated/test/TestableElectionStorage.sol:TestableElectionStorage"

[contract.TestableEpochStorage]
artifact = "contracts/generated/test/TestableEpochStorage.sol:TestableEpochStorage"

#TODO use create 2 and hardcode the contract addresses as settings
[contract.WormholeMock]
artifact = "contracts/mocks/WormholeMock.sol:WormholeMock"
args = ["10002"]

[contract.WormholeRelayerMock]
artifact = "contracts/mocks/WormholeRelayerMock.sol:WormholeRelayerMock"
args = ["<%= contracts.WormholeMock.address %>"]

# Core Router + Testable modules
[router.TestRouter]
contracts = [
    # Extend Original Core Router
    "CoreRouter",
    # Testable storage contracts
    "TestableCouncilStorage",
    "TestableBallotStorage",
    "TestableSnapshotVotePowerStorage",
    "TestableElectionSettingsStorage",
    "TestableElectionStorage",
    "TestableEpochStorage"
]

[invoke.upgrade_core_proxy]
target = ["InitialProxy"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.TestRouter.address %>"]
factory.GovernanceProxy.abiOf = ["TestRouter"]
factory.GovernanceProxy.event = "Upgraded"
factory.GovernanceProxy.arg = 0
factory.GovernanceProxy.highlight = true
