# THIS IS THE SATELLITE CHAIN, WORMHHOLE CHAIN ID 43 = Snaxchain chain 2192, WORMHOLE CHAIN ID 24 = OP MAINNET https://docs.wormhole.com/wormhole/reference/constants#chain-ids

name = "synthetix-snapshot-mock"
description = "On-chain voting for synthetix councils"
version = "1"
preset = "test-on-mainnet"

[setting.salt]
defaultValue = "governance-test-on-mainnet"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true
