name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "<%= package.version %>"

include = ["./cannonfile.toml"]

[setting.owner]
defaultValue = "0x431D454Bd4d352A0b1f45AE11EF1182bBEec6a7B"

[setting.salt]
defaultValue = "governance-test-v0"

[setting.wormhole_core]
defaultValue = "0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78" # https://docs.wormhole.com/wormhole/reference/constants

[setting.wormhole_relayer]
defaultValue = "0x7B1bD7a6b4E61c2a123AC6BC2cbfC614437D0470" # https://docs.wormhole.com/wormhole/reference/constants

[setting.initial_council_member]
defaultValue = "<%= settings.owner %>"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true

[invoke.set_registered_emitters]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setRegisteredEmitters"
args = [
    [
        "10002",
        "10005",
    ],
    [
        "0x4066a172DD5D21E4f787C07D3118D0876296750B",
        "0x4066a172DD5D21E4f787C07D3118D0876296750B",
    ],
]

[invoke.set_snapshot_record]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setSnapshotContract"
args = ["<%= contracts.SnapshotRecordMock.address %>", true]
