name = "synthetix-snapshot-record-mock"
description = "On-chain voting for synthetix councils - Snapshot record mock auxiliary contract"
version = "<%= package.version %>"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
