name = "synthetix-ambassador-council"
description = "On-chain voting for synthetix Ambassador Council"
version = "<%= package.version %>"

[setting.salt]
defaultValue = "synthetix-ambassador-council"

[setting.council_proxy_address]
defaultValue = "0x37fAc8c146889333734015B0C942b620aCfeeff8"

[setting.council_token_name]
defaultValue = "Synthetix Ambassador Council Token"

[setting.council_token_symbol]
defaultValue = "SNX-ACT"

[contract.CoreModule]
artifact = "CoreModule"
create2 = true

[contract.AssociatedSystemsModule]
artifact = "contracts/modules/core/AssociatedSystemsModule.sol:AssociatedSystemsModule"

[contract.ElectionModule]
artifact = "ElectionModule"

[contract.ElectionInspectorModule]
artifact = "ElectionInspectorModule"

[contract.CouncilTokenModule]
artifact = "CouncilTokenModule"

[router.CoreRouter]
contracts = [
  "AssociatedSystemsModule",
  "ElectionModule",
  "ElectionInspectorModule",
  "CoreModule",
]
depends = [
  "contract.AssociatedSystemsModule",
  "contract.ElectionModule",
  "contract.ElectionInspectorModule",
  "contract.CoreModule",
]

[invoke.upgrade_core_proxy]
target = ["<%= settings.council_proxy_address %>"]
abi = ["CoreModule"]
from = "<%= settings.owner %>"
func = "upgradeTo"
args = ["<%= contracts.CoreRouter.address %>"]
factory.CoreProxy.abiOf = ["CoreRouter"]
factory.CoreProxy.event = "Upgraded"
factory.CoreProxy.arg = 0
depends = ["router.CoreRouter"]

[router.CouncilTokenRouter]
contracts = [
  "CouncilTokenModule",
  "CoreModule",
]
depends = [
  "contract.CouncilTokenModule",
  "contract.CoreModule"
]

[invoke.init_council_token]
target = ["CoreProxy"]
from = "<%= settings.owner %>"
func = "initOrUpgradeNft"
args = [
  "<%= formatBytes32String('councilToken') %>",
  "Synthetix Governance Token",
  "SNXGOV",
  "https://synthetix.io",
  "<%= contracts.CouncilTokenRouter.address %>"
]
depends = [
  "invoke.upgrade_core_proxy",
  "router.CouncilTokenRouter"
]
factory.CouncilTokenProxy.abiOf = ["CouncilTokenRouter"]
factory.CouncilTokenProxy.event = "AssociatedSystemSet"
factory.CouncilTokenProxy.arg = 2

[invoke.init_election_module]
target = ["CoreProxy"]
func = "initOrUpgradeElectionModule(address[],uint8,uint64,uint64,uint64,address)"
args = [
  ["<%= settings.init_council_member %>"],
  "1",
  "<%= settings.epoch_start %>",
  "<%= settings.epoch_start + 86400 * settings.voting_period_duration %>",
  "<%= settings.epoch_start + 86400 * settings.epoch_duration %>",
  "<%= contracts.DebtShareMock.address %>",
]
from = "<%= settings.owner %>"
depends = ["invoke.init_council_token", "contract.DebtShareMock"]
