# THIS IS THE MOTHERSHIP CHAIN, WORMHHOLE CHAIN ID 43 = Snaxchain chain 2192, WORMHOLE CHAIN ID 24 = OP MAINNET https://docs.wormhole.com/wormhole/reference/constants#chain-ids

name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "1"
preset = "test-on-mainnet"

include = ["./cannonfile.toml", "./tomls/testable-contracts.toml"]

[setting.owner]
defaultValue = "0xe2163dd599067919d1e9108929b568Bf41D3A420"

[setting.salt]
defaultValue = "governance-test-on-mainnet"

[setting.wormhole_core]
defaultValue = "0xc1BA3CC4bFE724A08FbbFbF64F8db196738665f4" # https://explorer.snaxchain.io/address/0xc1BA3CC4bFE724A08FbbFbF64F8db196738665f4

[setting.wormhole_relayer]
defaultValue = "0x27428DD2d3DD32A4D7f7C497eAaa23130d894911" # https://explorer.snaxchain.io/address/0x27428DD2d3DD32A4D7f7C497eAaa23130d894911

[setting.initial_council_member]
defaultValue = "<%= settings.owner %>"

[setting.minimum_active_members]
defaultValue = "1"

[setting.initial_nomination_period_start_date]
defaultValue = "0" # defaults to "block.timestamp + administration_period_duration" when given "0"

[setting.administration_period_duration]
defaultValue = "60" # days

[setting.nomination_period_duration]
defaultValue = "15" # days

[setting.voting_period_duration]
defaultValue = "15" # days

[router.CoreRouter]
contracts = [
    # Core Contracts
    "AssociatedSystemsModule",
    "ElectionInspectorModule",
    "ElectionModule",
    "SnapshotVotePowerModule",
    "InitialModuleBundle",

    # Testable storage contracts
    "TestableCouncilStorage",
    "TestableBallotStorage",
    "TestableSnapshotVotePowerStorage",
    "TestableElectionSettingsStorage",
    "TestableElectionStorage",
    "TestableEpochStorage",
]

# [invoke.set_registered_emitters]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setRegisteredEmitters"
# args = [["43", "24"], ["contracts.GovernanceProxy.address", "contracts.GovernanceProxy.address"]]

[invoke.set_gas_limit]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setGasLimit"
args = ["10000000"]
