name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "<%= package.version %>"

include = ["./cannonfile.toml"]

[setting.owner]
defaultValue = "0x73570075092502472e4b61a7058df1a4a1db12f2"

[setting.salt]
defaultValue = "governance-test-v3"

[setting.wormhole_core]
defaultValue = "0x31377888146f3253211EFEf5c676D41ECe7D58Fe" # https://docs.wormhole.com/wormhole/reference/constants

[setting.wormhole_relayer]
defaultValue = "0x93BAD53DDfB6132b0aC8E37f6029163E63372cEE" # https://docs.wormhole.com/wormhole/reference/constants

[setting.initial_council_member]
defaultValue = "<%= settings.owner %>"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true

[invoke.set_registered_emitters]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setRegisteredEmitters"
args = [["10003"], ["0xD9fA68AD1Cc69EB1e72B043ABe313c0191a38cB1"]]

[invoke.set_snapshot_record]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setSnapshotContract"
args = ["<%= contracts.SnapshotRecordMock.address %>", true]
