name = "synthetix-governance"
version = "<%= package.version %>-test-sat"
include = ["cannonfile.satellite.toml", "tomls/ccip.test.toml"]

# [contract.SnapshotRecordMock]
# artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"

# # Testable storage contracts
# [contract.TestableCouncilStorage]
# artifact = "contracts/generated/test/TestableCouncilStorage.sol:TestableCouncilStorage"

# [contract.TestableBallotStorage]
# artifact = "contracts/generated/test/TestableBallotStorage.sol:TestableBallotStorage"

# [contract.TestableElectionSettingsStorage]
# artifact = "contracts/generated/test/TestableElectionSettingsStorage.sol:TestableElectionSettingsStorage"

# [contract.TestableElectionStorage]
# artifact = "contracts/generated/test/TestableElectionStorage.sol:TestableElectionStorage"

# # Core Router + Testable modules
# [router.TestRouter]
# contracts = [
#     # Extend Original Core Router
#     "CoreRouter",
#     # Testable storage contracts
#     "TestableCouncilStorage",
#     "TestableBallotStorage",
#     "TestableElectionSettingsStorage",
#     "TestableElectionStorage",
# ]

# [invoke.upgrade_core_proxy]
# target = ["InitialProxy"]
# from = "<%= settings.owner %>"
# func = "upgradeTo"
# args = ["<%= contracts.TestRouter.address %>"]
# factory.CoreProxy.abiOf = ["TestRouter"]
# factory.CoreProxy.event = "Upgraded"
# factory.CoreProxy.arg = 0