name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "5"
preset = "test"

include = ["./cannonfile.satellite.toml", "./tomls/testable-contracts.toml"]

[setting.owner]
defaultValue = "0x73570075092502472E4b61A7058Df1A4a1DB12f2"

[setting.salt]
defaultValue = "governance-test-v5"

[setting.wormhole_core]
defaultValue = "0x6b9C8671cdDC8dEab9c719bB87cBd3e782bA6a35" # https://docs.wormhole.com/wormhole/reference/constants

[setting.wormhole_relayer]
defaultValue = "0x7B1bD7a6b4E61c2a123AC6BC2cbfC614437D0470" # https://docs.wormhole.com/wormhole/reference/constants

[setting.initial_council_member]
defaultValue = "<%= settings.owner %>"

[setting.initial_epoch_index]
defaultValue = "0"

[setting.initial_epoch_start_date]
defaultValue = "0"

[setting.initial_nomination_period_start_date]
defaultValue = "0"

[setting.initial_voting_period_start_date]
defaultValue = "0"

[setting.initial_epoch_end_date]
defaultValue = "0"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true

[router.CoreRouter]
contracts = [
    # Satellite Core Contracts
    "AssociatedSystemsModule",
    "ElectionModuleSatellite",
    "SnapshotVotePowerModule",
    "InitialModuleBundle",

    # Testable storage contracts
    "TestableCouncilStorage",
    "TestableBallotStorage",
    "TestableSnapshotVotePowerStorage",
    "TestableElectionSettingsStorage",
    "TestableElectionStorage",
    "TestableEpochStorage",
]

[invoke.set_balance_of_on_period]
target = ["SnapshotRecordMock"]
from = "<%= settings.owner %>"
func = "setBalanceOfOnPeriod"
args = ["<%= settings.owner %>", "100", "1"]

# [invoke.set_snapshot_record]
# target = ["GovernanceProxy"]
# from = "<%= settings.owner %>"
# func = "setSnapshotContract"
# args = ["<%= contracts.SnapshotRecordMock.address %>", true]

[invoke.set_registered_emitters]
target = ["GovernanceProxy"]
from = "<%= settings.owner %>"
func = "setRegisteredEmitters"
args = [["10005"], ["0xCf84c9C2be639AE363713857d797e857Ba9B89c3"]]
