name = "synthetix-snapshot-record-mock"
description = "On-chain voting for synthetix councils - Snapshot record mock auxiliary contract"
version = "<%= package.version %>"

[setting.salt]
defaultValue = "snapshot-record-mock"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true
