name = "synthetix-governance"
description = "On-chain voting for synthetix councils"
version = "<%= package.version %>"

include = ["./cannonfile.toml"]

[setting.owner]
defaultValue = "0xf39fd6e51aad88f6f4ce6ab8827279cfffb92266"

[setting.salt]
defaultValue = "governance"

[setting.wormhole_core]
defaultValue = "0x4a8bc80Ed5a4067f1CCf107057b8270E0cC11A78" # https://docs.wormhole.com/wormhole/reference/constants

[setting.wormhole_relayer]
defaultValue = "0x7B1bD7a6b4E61c2a123AC6BC2cbfC614437D0470" # https://docs.wormhole.com/wormhole/reference/constants

[setting.initial_council_member]
defaultValue = "<%= settings.owner %>"

[contract.SnapshotRecordMock]
artifact = "contracts/mocks/SnapshotRecordMock.sol:SnapshotRecordMock"
salt = "<%= settings.salt %>"
create2 = true
